disabled_rules: # rule identifiers to exclude from running
        - trailing_whitespace
        - todo
        - nesting
        - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
        - Carthage
        - Pods
line_length:
        warning: 300
        error: 600
function_body_length:
        warning: 60
        error: 100
